### ISSUE TITLE
Vercel部署后绑定自己域名，API用不了，始终返回没有参数

### ISSUE THREAD

**Issue by puexine** [0wQ/next-smtp-proxy#4]

**Comment by 0wQ** [comment]
我这边测试没有问题，你可以试一下 https://hopp.sh/r/NHVYeYbsKWhs

![image](https://github.com/0wQ/next-smtp-proxy/assets/20741439/241925d9-3f80-4f5c-86df-effd63267a12)

**Comment by puexine** [comment]
找到原因了，QQ邮箱的问题，465、587端口好像总是有一个会出问题，连接超时
